// AUTO-GENERATED by scripts/gen-engine-manifest.mjs — do not edit by hand.
// Pyodide 0.27.0 (Python 3.12.7).

export const PYODIDE_VERSION = '0.27.0';
export const PYODIDE_CDN = 'https://cdn.jsdelivr.net/pyodide/v0.27.0/full/';

/** Files fetched by loadPyodide() itself (exact sizes from the npm package). */
export const CORE_FILES = [
  {
    "file": "pyodide.mjs",
    "bytes": 13879
  },
  {
    "file": "pyodide.asm.js",
    "bytes": 1253545
  },
  {
    "file": "pyodide.asm.wasm",
    "bytes": 10104029
  },
  {
    "file": "python_stdlib.zip",
    "bytes": 2358641
  },
  {
    "file": "pyodide-lock.json",
    "bytes": 106813
  }
];

/** Wheels per package; `bytes` are estimates until Content-Length is known. */
export const PACKAGES = {
  "numpy": {
    "file": "numpy-2.0.2-cp312-cp312-pyodide_2024_0_wasm32.whl",
    "sha256": "a6ccf853fa81e17c00ef594298410284a9cdde836efd7664dcc28c3b7ecad819",
    "depends": [],
    "bytes": 3600000
  },
  "scipy": {
    "file": "scipy-1.14.1-cp312-cp312-pyodide_2024_0_wasm32.whl",
    "sha256": "79bef26f529e6bd48def51d72a3fa3b03cbdf6df224859a825c1de0f34ef364c",
    "depends": [
      "numpy",
      "openblas"
    ],
    "bytes": 13500000
  },
  "openblas": {
    "file": "openblas-0.3.26.zip",
    "sha256": "ab914da96f9ae92417d71f3834f679b119f4bdfdb9da8f8a64c41ceb454e6726",
    "depends": [],
    "bytes": 1600000
  }
};
